version: '3.5'

services:
  postgres:
    container_name: postgres
    image: 'postgres:15'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    restart: unless-stopped
    networks:
      - testnet
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql

  # Testnet
  wallet-backend:
    container_name: wallet-backend
    build:
      context: ../..
      dockerfile: ./packages/wallet-backend/Dockerfile.dev
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 3003
      DB_URL: ${WALLET_BACKEND_DB_URL}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 2630000
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 2630000
      RAPYD_API: https://sandboxapi.rapyd.net/v1
      RAPYD_ACCESS_KEY: ${RAPYD_ACCESS_KEY}
      RAPYD_SETTLEMENT_EWALLET: ${RAPYD_SETTLEMENT_EWALLET}
      RAPYD_SECRET_KEY: ${RAPYD_SECRET_KEY}
    restart: always
    networks:
      - testnet
    ports:
      - '3003:3003'
      - '9229:9229' # Map debugger port to local machine's port 9229

  redis:
    image: 'redis:7'
    restart: unless-stopped
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1

volumes:
  pg-data:
